In [22]:
import scanpy as sc
import anndata as ad
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import median_abs_deviation
import numpy as np
import os
import re
from pathlib import Path
from anndata.experimental import concat_on_disk
import gc

In [ ]:
# # Read files in batches and concatenate incrementally using backed mode

# dir = Path("/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/")
# all_files = sorted(dir.glob("*.h5"))[:100]  # Stop at 100 files
# print(f"Total files to process: {len(all_files)}")

# # Create output zarr store (more efficient than h5ad for incremental writes)
# output_zarr = "dataset6_combined.zarr"
# adata = None

# for file_idx, file in enumerate(all_files, 1):
#     sample_name = file.stem
#     print(f"\nProcessing file {file_idx}/{len(all_files)}: {sample_name}")
    
#     try:
#         a = sc.read_10x_h5(file)
#         a.var_names_make_unique()
#         a.obs["sample"] = sample_name
        
#         if adata is None:
#             # Initialize with first file
#             adata = a
#             print(f"  Initialized with shape {adata.shape}")
#         else:
#             # Concatenate and save to zarr to free memory
#             adata = ad.concat([adata, a], axis=0, join='outer')
#             adata.obs_names_make_unique()
            
#             # Every 10 files, write to zarr and reload to free memory
#             if file_idx % 10 == 0:
#                 print(f"  Checkpoint at {file_idx} files: writing to zarr...")
#                 adata.write_zarr(output_zarr, mode='w')
#                 del adata
#                 gc.collect()
#                 adata = ad.read_zarr(output_zarr)
#                 print(f"  Current shape: {adata.shape}")
#             else:
#                 print(f"  Current shape: {adata.shape}")
                
#     except Exception as e:
#         print(f"  Error: {e}")
#         gc.collect()
#         continue

# # Final write
# print(f"\nFinal write to zarr...")
# adata.write_zarr(output_zarr, mode='w')
# print(f"Final shape: {adata.shape}")
# print("✓ Data saved to zarr and loaded into adata object")

:

:

:

In [ ]:
# # Extract and create GSM id column in obs
# adata.obs["GSM_id"] = adata.obs["sample"].str.extract(r"(GSM\d+)")
# display(adata.obs["GSM_id"].nunique())
# adata.obs

50

,sample,GSM_id
b0fe466cb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886
b0fe4720b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886
b0fe47a2b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886
b0fe481ab10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886
b0fe489cb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886
...,...,...
2860b17ab11811ee9ee3725e64acc2b0-GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935
2860b1e8b11811ee9ee3725e64acc2b0-GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935
2860b26ab11811ee9ee3725e64acc2b0-GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935
2860b2d8b11811ee9ee3725e64acc2b0-GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935
2860b350b11811ee9ee3725e64acc2b0-GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935_fRNA_B172_PB03429-001_labeled,GSM8464935

In [ ]:
# # inspect matrix (check whole numbers)
# pd.DataFrame(
#     adata.X[:10, :20].toarray(),
#     index=adata.obs_names[:10],
#     columns=adata.var_names[:20]
# )

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,RNF223,C1orf159,TTLL10,TNFRSF18,TNFRSF4,SDF4,B3GALT6,C1QTNF12,UBE2J2,SCNN1D,ACAP3,PUSL1
b0fe466cb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,1,0,0,0,0,0,0,5,0,0,0,0,1,0
b0fe4720b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0
b0fe47a2b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,3,0,0,0,0,3,0,0,0,0,0,0,6,0,0,4,0,2,0
b0fe481ab10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,3,0,0,0,0,0,0,2,0,0,0,0,0,0
b0fe489cb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,2,0,0,0,0,1,0,0,0,0,0,0,1,2,0,0,0,0,0
b0fe491eb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,3,0,0,1,0,0,0,2,0,0,0,0,0,0
b0fe498cb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,2,0,4,0
b0fe4a04b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,1,0,0,0,0,1,0,0,0,0,0,0,5,0,0,1,0,1,0
b0fe4b12b10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0
b0fe4b9eb10b11ee839e721e39c5c05a-GSM8464886_fRNA_B172_PB03173-001_labeled,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [23]:
# read in and inspect metadata text file

file_path = "/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067.txt"

with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
    text = f.read()


idx = text.find("^SAMPLE =")
print(text[idx:idx+2000])

^SAMPLE = GSM8464886
!Sample_title = PB03173-001 flex scRNA-seq
!Sample_geo_accession = GSM8464886
!Sample_status = Public on Sep 12 2025
!Sample_submission_date = Aug 16 2024
!Sample_last_update_date = Sep 12 2025
!Sample_type = SRA
!Sample_channel_count = 1
!Sample_source_name_ch1 = Blood
!Sample_organism_ch1 = Homo sapiens
!Sample_taxid_ch1 = 9606
!Sample_characteristics_ch1 = tissue: Blood
!Sample_characteristics_ch1 = cell type: PBMC
!Sample_characteristics_ch1 = subject id: SF3001
!Sample_characteristics_ch1 = age at_enrollment: 52
!Sample_characteristics_ch1 = Sex: Female
!Sample_characteristics_ch1 = race: African American
!Sample_characteristics_ch1 = cmv status: Negative
!Sample_characteristics_ch1 = batch id: B172
!Sample_characteristics_ch1 = sample bridging_control: FALSE
!Sample_characteristics_ch1 = pooled sample_id: B172-PC
!Sample_characteristics_ch1 = probe barcode_id: BC010
!Sample_molecule_ch1 = other
!Sample_extract_protocol_ch1 = PBMCs were removed from liquid nitrogen and immediately thawed in a 37°C water bath. Cells were diluted dropwise into 40 mL AIM V media (Thermo Fisher Scientific) pre-warmed to 37°C. Cells were pelleted at 400 x g for 5–10 min at 4–10°C, resuspended in 5 mL cold AIM V media, and counted using a Cellometer Spectrum or Cellaca. After adding 30 mL cold AIM V media, cells were re-pelleted and resuspended to the appropriate concentrations for scRNAseq.
!Sample_extract_protocol_ch1 = scRNAseq libraries were generated using a modified 10x genomics flex single cell gene expression assay. Sample libraries were constructed across different batches, with the addition of a common healthy donor leukopak sample in each library as batch control. Libraries were sequenced on the Illumina Novaseq 6000 or X platform.
!Sample_description = SRR30239415, SRR30239414, SRR30239432, SRR30239431, SRR30239430, SRR30239429, SRR30239428, SRR30239427, SRR30239426, SRR30239425, SRR30239424, SRR30239423, SRR30239421, SRR30239419, SRR30239418, SRR3023

In [24]:
# turn metadata text file into dataframt to merge with adata.obs, extracting age, sex, race, batch, and subject ID (SF_id)

dir_meta = "/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067.txt"
records = []
current = None

with open(dir_meta, "r", encoding="utf-8", errors="ignore") as f:
    for line in f:
        line = line.rstrip("\n")

        if line.startswith("^SAMPLE = "):
            if current is not None:
                records.append(current)
            current = {"GSM_id": line.split(" = ", 1)[1]}

        elif current is not None:
            if line.startswith("!Sample_title = "):
                current["sample_title"] = line.split(" = ", 1)[1]

            elif line.startswith("!Sample_characteristics_ch1 = "):
                val = line.split(" = ", 1)[1]

                if val.startswith("subject id:"):
                    current["SF_id"] = val.split(":", 1)[1].strip()
                elif val.startswith("age at_enrollment:"):
                    current["age"] = val.split(":", 1)[1].strip()
                elif val.startswith("Sex:"):
                    current["gender"] = val.split(":", 1)[1].strip()
                elif val.startswith("race:"):
                    current["race"] = val.split(":", 1)[1].strip()
                elif val.startswith("batch id:"):
                    current["batch"] = val.split(":", 1)[1].strip()

    if current is not None:
        records.append(current)

geo_meta = pd.DataFrame(records)

geo_meta = geo_meta[["GSM_id", "SF_id", "age", "gender", "race", "batch"]].drop_duplicates()
geo_meta.head()

       GSM_id   SF_id age  gender              race batch
0  GSM8464886  SF3001  52  Female  African American  B172
1  GSM8464887  SF3006  68    Male   American Indian  B172
2  GSM8464888  SF3016  47    Male         Caucasian  B171
3  GSM8464889  SF3020  70  Female             Asian  B155
4  GSM8464890  SF3024  50  Female   American Indian  B172

In [25]:
# add age bin column to geo_meta

bins = [39, 49, 59, 69, 79, 200]
labels = ["40-50", "50-59", "60-69", "70-79", "80+"]

geo_meta["age"] = pd.to_numeric(geo_meta["age"], errors="coerce")

geo_meta["age_bin"] = pd.cut(
    geo_meta["age"],
    bins=bins,
    labels=labels,
    right=True
)

geo_meta

,GSM_id,SF_id,age,gender,race,batch,age_bin
0,GSM8464886,SF3001,52.0,Female,African American,B172,50-59
1,GSM8464887,SF3006,68.0,Male,American Indian,B172,60-69
2,GSM8464888,SF3016,47.0,Male,Caucasian,B171,40-50
3,GSM8464889,SF3020,70.0,Female,Asian,B155,70-79
4,GSM8464890,SF3024,50.0,Female,American Indian,B172,50-59
...,...,...,...,...,...,...,...
247,GSM8465133,na,NaN,pooled male and female,na,B172,NaN
248,GSM8465134,na,NaN,pooled male and female,na,B172,NaN
249,GSM8465135,na,NaN,pooled male and female,na,B173,NaN
250,GSM8465136,na,NaN,pooled male and female,na,B173,NaN
251,GSM8465137,na,NaN,pooled male and female,na,B173,NaN

In [ ]:
# # subset metadata to only samples in adata

# adata_gsm_ids = adata.obs["GSM_id"].unique()
# geo_meta = geo_meta[geo_meta["GSM_id"].isin(adata_gsm_ids)]
# print(geo_meta.shape)

(50, 6)

In [ ]:
# # merge age and metadata with adata.obs on donor_id (for only the 50 samples we have)
# adata.obs = adata.obs.merge(geo_meta, on='GSM_id', how='left')
# adata.obs.head()

/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:740: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    [0, 1, 2, 3, 4]

    Inferred to be: integer

  value_idx = self._prep_dim_index(value.index, attr)

,sample,GSM_id,SF_id,age,gender,race,batch
0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52,Female,African American,B172
1,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52,Female,African American,B172
2,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52,Female,African American,B172
3,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52,Female,African American,B172
4,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52,Female,African American,B172

In [ ]:
# # calculate sample counts and proportions of samples in age bands (50-59, 60-69, 70-79, 80+), for age-matching with PD dataset

# # extract from obs, one row per sample with age and diagnosis
# sample_ages = adata.obs[["GSM_id", "age"]].drop_duplicates().copy()
# sample_ages["age"] = pd.to_numeric(sample_ages["age"], errors="coerce")

# bins = [39, 49, 59, 69, 79, 200]
# labels = ["40-50", "50-59", "60-69", "70-79", "80+"]

# sample_ages["age_band"] = pd.cut(sample_ages["age"], bins=bins, labels=labels, right=True, include_lowest=True)

# # overall counts and proportions of samples per age band
# control_counts = sample_ages["age_band"].value_counts().reindex(labels, fill_value=0)
# age_band_props = (control_counts / control_counts.sum()).round(3)
# control_counts = pd.DataFrame({"count": control_counts, "proportion": age_band_props})

# display(control_counts)

       count  proportion
40-50     13        0.26
50-59     13        0.26
60-69     10        0.20
70-79     12        0.24
80+        2        0.04

In [29]:
# get target age bin counts: import all tables of count by age band and diagnosis from other datasets

d1 = pd.read_csv("/rds/general/user/ztb25/home/PBMC_datasets/1/age_band_props_by_diagnosis.csv", index_col=0)
d2 = pd.read_csv("/rds/general/user/ztb25/home/PBMC_datasets/4/age_band_props_by_diagnosis.csv", index_col=0)
d3 = pd.read_csv("/rds/general/user/ztb25/home/PBMC_datasets/5/age_band_props_by_diagnosis.csv", index_col=0)

In [30]:
# using the tables, calculate the total number of samples in the PD and AD diagnosis subgroups in all samples

d1["dataset"] = "dataset1"
d2["dataset"] = "dataset4"
d3["dataset"] = "dataset5"
disease_counts = pd.concat([d1, d2, d3], ignore_index=False)

# take only the PD or AD rows (from the index)
disease_counts = disease_counts.loc[disease_counts.index.isin(["PD", "AD"])]


# create a total row (for all but the dataset column)
disease_counts.loc["Total"] = disease_counts.drop(columns=["dataset"]).sum()
display(disease_counts)

# get and overall total sum of disease samples
total_samples = disease_counts.loc["Total"].sum()
display(total_samples)

           40-50  50-59  60-69  70-79  80+   dataset
diagnosis
PD           0.0    0.0    2.0    2.0  0.0  dataset1
AD           1.0    2.0    8.0    9.0  8.0  dataset4
PD           0.0    0.0   10.0    4.0  0.0  dataset5
Total        1.0    2.0   20.0   15.0  8.0       NaN

46.0

In [ ]:
# create a target age band counts for the control samples (from the total row of the total_samples)

target_counts = {
    "40-50": 1,
    "50-59": 2,
    "60-69": 20,
    "70-79": 15,
    "80+": 8
}

np.random.seed(42)

# subset geo_meta to target age band counts, randomly sampling from each age band if there are more samples than the target count for that band, and taking all samples if there are fewer than the target count for that band

selected_rows = []

for age_bin, target_n in target_counts.items():
    pool = geo_meta[geo_meta["age_bin"] == age_bin].copy()
    
    n_keep = min(target_n, len(pool))
    
    if n_keep > 0:
        sampled = pool.sample(n=n_keep, replace=False, random_state=42)
        selected_rows.append(sampled)

geo_meta_subset = pd.concat(selected_rows, ignore_index=True)
geo_meta_subset

        GSM_id   SF_id   age  gender                       race batch age_bin
0   GSM8465062  SF4482  49.0  Female                      Asian  B151   40-50
1   GSM8464979  SF4270  54.0  Female                  Caucasian  B172   50-59
2   GSM8464886  SF3001  52.0  Female           African American  B172   50-59
3   GSM8464990  SF4305  62.0  Female  Hispanic or Latino origin  B173   60-69
4   GSM8464947  SF4182  63.0  Female                  Caucasian  B172   60-69
5   GSM8464983  SF4285  60.0  Female                  Caucasian  B173   60-69
6   GSM8464974  SF4260  61.0  Female                  Caucasian  B171   60-69
7   GSM8464962  SF4229  69.0  Female                  Caucasian  B173   60-69
8   GSM8464994  SF4311  68.0  Female                  Caucasian  B171   60-69
9   GSM8464972  SF4254  66.0  Female                  Caucasian  B151   60-69
10  GSM8464945  SF4166  65.0    Male                  Caucasian  B171   60-69
11  GSM8464930  SF4127  64.0  Female                  Caucasian  B171   60-69
12  GSM8464963  SF4235  60.0  Female  Hispanic or Latino origin  B172   60-69
13  GSM8464935  SF4140  65.0    Male                  Caucasian  B172   60-69
14  GSM8465026  SF4403  60.0    Male                  Caucasian  B155   60-69
15  GSM8464887  SF3006  68.0    Male            American Indian  B172   60-69
16  GSM8464911  SF4068  64.0  Female                  Caucasian  B172   60-69
17  GSM8464966  SF4239  62.0  Female                  Caucasian  B172   60-69
18  GSM8464992  SF4309  61.0  Female                  Caucasian  B171   60-69
19  GSM8464915  SF4081  64.0  Female  Hispanic or Latino origin  B173   60-69
20  GSM8464944  SF4162  69.0    Male                  Caucasian  B171   60-69
21  GSM8464901  SF4039  66.0    Male           African American  B171   60-69
22  GSM8464903  SF4049  68.0    Male  Hispanic or Latino origin  B155   60-69
23  GSM8465100  SF4603  77.0    Male                      Asian  B155   70-79
24  GSM8465027  SF4404  77.0  Female                      Asian  B173   70-79
25  GSM8465032  SF4417  76.0    Male                  Caucasian  B172   70-79
26  GSM8465105  SF4612  73.0    Male                  Caucasian  B172   70-79
27  GSM8465086  SF4557  77.0    Male                      Asian  B171   70-79
28  GSM8465102  SF4606  74.0    Male                      Asian  B172   70-79
29  GSM8464912  SF4072  77.0  Female                  Caucasian  B172   70-79
30  GSM8464936  SF4144  74.0  Female                      Asian  B172   70-79
31  GSM8464926  SF4116  76.0  Female                      Asian  B155   70-79
32  GSM8464910  SF4065  75.0    Male                  Caucasian  B151   70-79
33  GSM8464917  SF4090  77.0    Male  Hispanic or Latino origin  B155   70-79
34  GSM8465021  SF4386  78.0    Male                  Caucasian  B155   70-79
35  GSM8465070  SF4515  76.0    Male                      Asian  B173   70-79
36  GSM8464995  SF4313  74.0  Female                  Caucasian  B151   70-79
37  GSM8464971  SF4246  74.0    Male                      Asian  B155   70-79
38  GSM8464998  SF4316  88.0  Female                  Caucasian  B173     80+
39  GSM8465089  SF4561  85.0  Female                  Caucasian  B173     80+
40  GSM8464899  SF4033  84.0    Male                  Caucasian  B173     80+
41  GSM8465099  SF4601  86.0  Female                  Caucasian  B172     80+
42  GSM8465030  SF4412  80.0    Male                  Caucasian  B172     80+
43  GSM8465007  SF4334  82.0  Female                  Caucasian  B172     80+
44  GSM8465061  SF4477  80.0  Female                  Caucasian  B155     80+
45  GSM8464925  SF4112  88.0    Male                  Caucasian  B171     80+

In [ ]:
# read in files with the selected GSM ids

# GSMs you want
selected_gsms = set(geo_meta_subset["GSM_id"].dropna().unique())

# folder with h5 files
dir = Path("/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/")

# all h5 files
all_files = sorted(dir.glob("*.h5"))

# keep only files whose name starts with one of the selected GSM IDs
files_to_read = [f for f in all_files if f.name.split("_")[0] in selected_gsms]

display(len(files_to_read))
display(files_to_read[:5])

46

[PosixPath('/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/GSM8464886_fRNA_B172_PB03173-001_labeled.h5'),
 PosixPath('/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/GSM8464887_fRNA_B172_PB03180-001_labeled.h5'),
 PosixPath('/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/GSM8464899_fRNA_B173_PB03171-001_labeled.h5'),
 PosixPath('/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/GSM8464901_fRNA_B171_PB03187-001_labeled.h5'),
 PosixPath('/rds/general/user/ztb25/home/PBMC_datasets/6/GSE275067_RAW/GSM8464903_fRNA_B155_PB03275-001_labeled.h5')]

In [39]:
meta_lookup = geo_meta_subset.set_index("GSM_id")

adatas = []

for file in files_to_read:
    gsm = file.name.split("_")[0]
    
    a = sc.read_10x_h5(file)
    a.var_names_make_unique()
    
    a.obs["sample"] = file.stem
    a.obs["GSM_id"] = gsm
    
    a.obs["SF_id"] = meta_lookup.loc[gsm, "SF_id"]
    a.obs["age"] = meta_lookup.loc[gsm, "age"]
    a.obs["sex"] = meta_lookup.loc[gsm, "gender"]
    a.obs["race"] = meta_lookup.loc[gsm, "race"]
    a.obs["age_bin"] = meta_lookup.loc[gsm, "age_bin"]
    
    adatas.append(a)

/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/rds/general/user/ztb25/home/miniforge3/envs/m10/lib/python3.11/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [41]:
adata = sc.concat(adatas, join="outer", index_unique="-")

In [42]:
adata

AnnData object with n_obs × n_vars = 1161819 × 18082
    obs: 'sample', 'GSM_id', 'SF_id', 'age', 'sex', 'race', 'age_bin'

In [45]:
adata.obs.head()

,sample,GSM_id,SF_id,age,sex,race,age_bin
b0fe466cb10b11ee839e721e39c5c05a-0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52.0,Female,African American,50-59
b0fe4720b10b11ee839e721e39c5c05a-0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52.0,Female,African American,50-59
b0fe47a2b10b11ee839e721e39c5c05a-0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52.0,Female,African American,50-59
b0fe481ab10b11ee839e721e39c5c05a-0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52.0,Female,African American,50-59
b0fe489cb10b11ee839e721e39c5c05a-0,GSM8464886_fRNA_B172_PB03173-001_labeled,GSM8464886,SF3001,52.0,Female,African American,50-59

In [ ]:
# # subset controls (from control_counts) within each age bin to match the disease samples (from disease_counts) counts per age group

# # calculate the number of controls to sample from each age band, based on the proportions in control_counts and the total number of disease samples
# control_counts["target_count"] = (control_counts["proportion"] * total_samples).round()
# display(control_counts)

       count  proportion  target_count
40-50     13        0.26          12.0
50-59     13        0.26          12.0
60-69     10        0.20           9.0
70-79     12        0.24          11.0
80+        2        0.04           2.0